version = 1
SPDX-PackageName = "bdp-elaborations"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/bdp-elaborations"

[[annotations]]
path = ["helm/**", ".github/**", ".gitignore", "LICENSE", ".editorconfig", "**/.gitignore", ".pre-commit-config.yaml", "**/.env.example", "**/.editorconfig", "**/**.txt", "**/Jenkinsfile-CI", "**/Jenkinsfile-Production-Archive", "**/Jenkinsfile-Testserver-Archive", "**/docker/**", "**/infrastructure/**", "**/documentation/**", "**/**/**.properties", "**/**/**.gif", "**/**/**.json", "**/**/**.csv", "**/**/**.pyc", "**/**/**.db", "**/**/**.cpg", "**/**/**.dbf", "**/**/**.prj", "**/**/**.qpj", "**/**/**.shp", "**/**/**.shx", "**/**/**.jsp", "**/**/**.css", "ts-model/doc/package-list", "environment-a22-averages/calls.http", "LocationReverseLookupService/package.json", "LocationReverseLookupService/Jenkinsfile", "LocationReverseLookupService/Jenkinsfile-Production", "**/go.sum"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["pollution_v2/weather/metro/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2006 Environment Canada"
SPDX-License-Identifier = "GPL-2.0-only"