version: "2.2"
    

services:
  worker:
    container_name: "pollution-connector"
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    command: celery -A pollution_connector.celery_configuration.celery_app worker --loglevel=INFO
    env_file:
      - .env
    networks:
      - pollution
    cpus: "0.5"
    mem_limit: 4096m


  scheduler:
    container_name: "pollution-connector-scheduler"
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    command: celery -A pollution_connector.celery_configuration.celery_app beat --loglevel=INFO
    env_file:
      - .env
    volumes:
       - pollution-connector-scheduler:/scheduler/
    networks:
       - pollution

  redis:
    image: redis:6.2
    container_name: "pollution-connector-redis"
    hostname: pollution-connector-redis
    restart: unless-stopped
    networks:
      - pollution
    volumes:
      - pollution-connector-redis:/data


networks:
  pollution:

volumes:
  pollution-connector-scheduler:
  pollution-connector-redis: