image:
  repository: 
  pullPolicy: IfNotPresent
  tag: "0.2.0" # Set this when upgrading chart with --set-value

env:
  BDP_BASE_URL: http://bdp-core.core.svc.cluster.local
  BDP_PROVENANCE_VERSION: 0.1.0
  BDP_PROVENANCE_NAME: el-dataset-watcher
  BDP_ORIGIN: el-dataset-watcher

  TS_API_BASE_URL: http://ninja-api.core.svc.cluster.local
  TS_API_REFERER: el-dataset-watcher

  ODH_TOKEN_URL: https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token
  ODH_CLIENT_ID: el-parking-free
  ODH_CLIENT_SECRET: 

  LOG_LEVEL: DEBUG

  CRON: 0 0/30 * * * *