# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.8"

services:
  app:
    image: python:3.12-slim
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    env_file:
      - .env
    command: >
      sh -c "pip install -r requirements.txt && python src/main.py"
